services:
  postgres:
    container_name: starter-db
    image: postgres:17-alpine
    ports:
      - "0.0.0.0:5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${DB_USER:-postgres}
      - POSTGRES_PASSWORD=${DB_PASSWORD:-postgres123}
      - POSTGRES_DB=${DB_NAME:-fastapi_db}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER:-postgres} -d ${DB_NAME:-fastapi_db}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  backend:
    container_name: starter-backend
    build: ./backend
    ports:
      - "0.0.0.0:8000:8000"
    volumes:
      - ./backend:/app
    environment:
      - DB_NAME=${DB_NAME:-fastapi_db}
      - DB_USER=${DB_USER:-postgres}
      - DB_PASSWORD=${DB_PASSWORD:-postgres123}
      - DB_HOST=postgres
      - DB_PORT=5432
      - CORS_ORIGINS=["https://obscure-barnacle-7vgwr7px5jvcrj4p-5173.app.github.dev", "https://*.app.github.dev", "http://0.0.0.0:5173", "https://*.githubpreview.dev", "https://*.github.dev"]
      - ENVIRONMENT=development
    depends_on:
      postgres:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/health"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    command: bash -c "python manage.py run"

  frontend:
    container_name: starter-frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "0.0.0.0:5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - VITE_API_URL=https://obscure-barnacle-7vgwr7px5jvcrj4p-8000.app.github.dev
    depends_on:
      backend:
        condition: service_healthy
    command: npm run dev

  docs:
    container_name: starter-docs
    build:
      context: .
      dockerfile: docs/Dockerfile
    ports:
      - "0.0.0.0:8001:8001"
    volumes:
      - ./docs:/usr/src/app/docs
      - ./mkdocs.yml:/usr/src/app/mkdocs.yml

volumes:
  postgres_data:
